import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DeleteResult, Repository } from 'typeorm';
import { UserEntity } from './user.entity';
import {
  GetSaltDto,
  CreateUserDto,
  AuthenticationDto,
  LoginResponseDto,
  DeleteUserDto,
  UpdateUserDto,
} from './user.dto';
import {
  INSTANCE_ID,
  SERVER_RANDOM_VALUE,
  sha256,
  sha512,
  addPadding,
  generateSessionIdentifier,
  rsaPublicEncrypt,
} from 'src/logic/security';

@Injectable()
export class UserService {
  constructor(
    @InjectRepository(UserEntity)
    private userRepository: Repository<UserEntity>,
  ) {}

  //TODO make all functions return Promise instead of Observable

  async create(dto: CreateUserDto): Promise<UserEntity> {
    if (!(await this.mailExists(dto.email))) {
      if (!(await this.userExists(dto.username))) {
        return await this.userRepository.save(dto);
      } else {
        throw new HttpException('username already in use', HttpStatus.CONFLICT);
      }
    } else {
      throw new HttpException('Email  already in use', HttpStatus.CONFLICT);
    }
  }

  /**
   * Updates a user account parameters specified in the request.
   * Returns the updated user.
   * @param dto
   */
  async update(dto: UpdateUserDto): Promise<UserEntity> {
    const userToUpdate = await this.findOne(dto.id);
    userToUpdate.email = dto.email;
    await this.userRepository.save(userToUpdate);
    return userToUpdate;
  }

  /**
   * Delete the user possessing the id specified in the request.
   * Returns the DeleteResult.
   * @param dto
   */
  delete(dto: DeleteUserDto): Promise<DeleteResult> {
    return this.userRepository.delete(dto.id);
  }

  /**
   * Returns a salt generated from the specified username and a client random value.
   * If the corresponding user does not exist, the random value is generated by the server.
   * @param dto
   */
  async getSalt(dto: GetSaltDto): Promise<string> {
    const user = await this.userRepository.findOne({ username: dto.username });
    if (user !== undefined) {
      return sha256(
        addPadding(dto.username + INSTANCE_ID + user.clientRandomValue, 128),
      );
    } else {
      return sha256(
        addPadding(dto.username + INSTANCE_ID + SERVER_RANDOM_VALUE, 128),
      );
    }
  }

  async authentication(dto: AuthenticationDto): Promise<LoginResponseDto> {
    const user = await this.userRepository.findOne({ username: dto.username });
    if (user !== undefined) {
      const key = sha512(dto.derivedAuthenticationKey);

      if (key === user.hashedAuthenticationKey) {
        const session = generateSessionIdentifier();
        user.sessionIdentifiers.push(session);
        await this.userRepository.save(user);

        const res = new LoginResponseDto();
        res.encryptedMasterKey = user.encryptedMasterKey;
        res.encryptedRsaPrivateSharingKey = user.encryptedRsaPrivateSharingKey;
        res.rsaPublicSharingKey = user.rsaPublicSharingKey;
        res.encryptedSessionIdentifier = rsaPublicEncrypt(
          user.rsaPublicSharingKey,
          session,
        );
        return res;
      } else
        throw new HttpException('Invalid credentials', HttpStatus.UNAUTHORIZED);
    } else
      throw new HttpException('Invalid credentials', HttpStatus.UNAUTHORIZED);
  }

  async findAll(): Promise<UserEntity[]> {
    return await this.userRepository.find();
  }

  async findOne(id: number): Promise<UserEntity> {
    const user = await this.userRepository.findOne({
      where: { id: id },
    });
    if (user === undefined) {
      throw new HttpException('user not found', HttpStatus.NOT_FOUND);
    }
    return user;
  }

  private async mailExists(email: string): Promise<boolean> {
    return !!(await this.userRepository.findOne({ email }));
  }

  private async userExists(username: string): Promise<boolean> {
    return !!(await this.userRepository.findOne({ username }));
  }
}
